version: "3.8"

volumes:
  postgres:

services:
  web:
    build: .
    container_name: web
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: db
    restart: always
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  nginx:
    image: nginx:1.21.6-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - db
      - web